### PR TITLE
Fixes and relocation

### PR DESCRIPTION
**Pull request by anf**
## Description

This PR addresses a few changes and fixes to the structure of the project and the readme file's display.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by Juptian** [comment]
Looks good to me, and if it works, which github is telling me it does, this should be fine. A lot of minor changes, mainly file directories and imports, but it will affect whether or not the bot runs!

**Comment by anf** [comment]
Alright @Juptian, thanks for reviewing, after doing some final checks I shall merge it.

**Comment by anf** [comment]
I have yet to handle some exceptions so this pr will take time to get merged.
image

**Comment by anf** [comment]
Things have gone a.. a bit too much problematic, I'm recreating this branch - let's start this fresh.

**Pull request closed without merging**
